### ISSUE TITLE
MEAToolbox Installer 1.1 won't run on Windows 10

### ISSUE THREAD

**Issue by fmccread** [mhyhu/MEA-ToolBox#1]
Hi,

I am encountering an issue where launching the MEAToolbox installer causes Windows to display an error message stating "This app can't run on your PC - To find a version for your PC, check with the software publisher".  I get this error with both the "(with runtime)" and "(without runtime)" installers:

![image](https://user-images.githubusercontent.com/63566522/175389325-4f985801-6fc6-46c1-95e2-68f298bb185f.png)

I'm currently running 64-bit Windows 10 Pro, version 21H2. 

So far I've tried running the compatibility troubleshooter and launching the installer in compatibility mode for Windows 7 and Windows 8, but am still encountering the error. I also asked a couple of colleagues if they could try downloading and launching the installer on their own PCs and they both encountered this same issue, so it doesn't seem to be isolated to just my system. 

As a temporary workaround, we managed to successfully launch the program by:
1. Downloading and installing the older MATLAB R2018b release from [mathworks.com/downloads](url).
2. Extracting '_Source Code MEA-ToolBox1.15.zip_' to a new folder.
3. Opening MATLAB R2018b and setting the path to this source code folder.
4. Adding the 'Animation Home Screen' and 'External' folders and all their sub-directories to the MATLAB path.
5. Running _Main_Menu_Toolbox.m_ from the MATLAB R2018b command window.

This requires you to have a valid MATLAB license with a number of different toolboxes though.

**Comment by mhyhu** [comment]
Hey fmccread,

My apologies for the late response!
First of all thank you for your interest in the toolbox!
We have not encountered this problem ourselves yet.
However after digging around a little I think I might have found a solution.

Based on the following answer from MATLAB themselves.
https://nl.mathworks.com/matlabcentral/answers/110839-when-installing-matlab-why-do-i-see-an-error-stating-this-app-can-t-run-on-your-pc-to-find-a-vers

The way to solve this issue perhaps is by ensuring that the executable is properly downloaded.
If i look at your image both the executables are 1kb which is odd.
Please take a look at the image below which has the correct sizes of the executables. 
![Toolbox](https://user-images.githubusercontent.com/67150479/175811840-c316c637-69fd-4214-881f-78eea6a105a2.png)

I have also compiled the executables on a windows 10 enterprise 21H2 version and added these executables in the same google drive that contains the test data in case downloading from GitHub is not properly working.  
https://drive.google.com/drive/folders/1IrS9-TnZHw8d7IW7TlJVqvXeNlGGVtY3?usp=sharing

When the executable is downloaded, I would recommend to use administration rights to install it. A window should pop up to guide one through the installation process. Depending on local security settings, a different window may pop up that says that it does not recognize the application and will not properly install it. In this case please select the option to allow it to run, which should enable normal installation. 

Please let me know if this works for you.

Best,
Michel

**Comment by fmccread** [comment]
Hi Michel,

Thanks for the response! I downloaded the new executable files from the Google Drive link and they launched and ran fine without any issues.

I'm now able to launch the standalone MEAToolbox application and use the "Set Parameters" button, however when I try to use the "Analyze File" or "Load File" buttons I get the following errors in the terminal window

Using Analyze File:
![image](https://user-images.githubusercontent.com/63566522/176494716-7b8ae627-d5df-4d96-9936-bb90a4c08d6b.png)

Using Load File:
![image](https://user-images.githubusercontent.com/63566522/176496218-09816011-3538-468a-8509-1e4dff702d6e.png)

I found a couple of MATLAB Answers threads about similar error messages and it sounds like the issue might be related to the application using the wrong MATLAB runtime? 
https://www.mathworks.com/matlabcentral/answers/554821-compiling-failing-using-matlab-2019b
https://www.mathworks.com/matlabcentral/answers/483205-app-designer-standalone-test-app-not-executing

Notably, the installer seems to be looking for the R2021b runtime rather than R2018b when I run it on my PC:
![image](https://user-images.githubusercontent.com/63566522/176497841-a86be3dc-f51d-4b94-bd65-79304ab1cb05.png)

Could be related? 

Cheers,
Fraser

**Comment by fmccread** [comment]
Works great now! 

I was able to analyze the provided sample data files and have been exploring the analyzed data without running into any issues.

Thanks for making this tool freely available and for providing thorough documentation on how to use/modify it. This should be an excellent resource for the field. 

Cheers,
Fraser

**Comment by mhyhu** [comment]
Hey Fraser,

I'm happy that it works for you now!
We hope it helps people to analyze their data a little more streamlined as we also struggled in the beginning.
If you have any suggestions for improvements, please let me know.
